# Generated by Django 3.0 on 2020-06-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0009_auto_20200607_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubIncidents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('env', models.CharField(max_length=256)),
                ('inj', models.CharField(max_length=256)),
                ('pd', models.CharField(max_length=256)),
                ('veh', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'SubIncidents',
            },
        ),
    ]
